#' Run LimoRhyde rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_limorhyde()`.
#' @param groups A vector with the groups in the experiment.
#' @param method_args Additional parameters passed to `limma::lmFit()` or
#'   `edgeR::vommLmFit()` depending on `data_type`.
#'
#' @importFrom limma lmFit eBayes topTable
#' @importFrom edgeR voomLmFit
#'
#' @returns A data frame
execute_limorhyde <- function(inputs, groups, method_args = list()) {
  # Combine and overwrite inputs with method_args
  inputs <- utils::modifyList(inputs, method_args)

  # Get function from inputs
  func <- inputs$func
  inputs$func <- NULL

  # If in method args, change robust and otherwise set to TRUE
  robust <- inputs$robust %||% TRUE

  # Run rhythmicity analysis
  if (func == "lmFit") {
    fit <- do.call(limma::lmFit, inputs)
    fit <- limma::eBayes(fit, trend = TRUE, robust = robust)

  } else if (func == "voomLmFit") {
    fit <- do.call(edgeR::voomLmFit, inputs)
    fit <- limma::eBayes(fit, robust = robust)
  }

  # Extract results
  if (is.null(groups) | length(groups) == 1) {
    # Get columns
    relev_cols <- grep("time_", colnames(inputs$design), value = TRUE)

    # Extract statistics
    df_res <- limma::topTable(fit, coef = relev_cols, number = Inf, sort.by = "none")

    # If a single group is present, add it
    if (length(groups) == 1) {
      df_res <- data.frame(
        group = groups,
        df_res
      )
    }

    # Add feature names
    df_res <- data.frame(
      feature = row.names(df_res),
      df_res
    )
  } else {
    ls_res <- list()
    for (grp in groups) {
      # Get columns
      relev_cols <- grep(paste0(grp, ".time_"), colnames(inputs$design), value = TRUE)

      # Extract statistics
      df_res_grp <- limma::topTable(fit, coef = relev_cols, number = Inf, sort.by = "none")

      # Rename interaction columns so they no longer include the group name
      colnames(df_res_grp) <- gsub("^group.+\\.(time_.*)", "\\1", colnames(df_res_grp))

      # Add feature names and group
      df_res_grp <- data.frame(
        feature = row.names(df_res_grp),
        group = grp,
        df_res_grp
      )

      # Add to list
      ls_res[[grp]] <- df_res_grp
    }

    # Collapse list into data frame
    df_res <- do.call(rbind, ls_res)
  }

  # Remove redundant row names
  row.names(df_res) <- NULL

  # Return results
  return(df_res)
}
