#' Run ARSER rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_arser()`
#' @param grp Group that is being analysed
#' @param ... Additional parameters passed to `MetaCycle::meta2d()`
#'
#' @importFrom MetaCycle meta2d
#'
#' @returns A list
execute_arser <- function(inputs, grp, ...) {
  # TODO: Figure out what to do about `parallelize` and `nCores`

  # Add arguments in `...` to `inputs`, giving precedence to `...` in case of
  # overlap
  dots <- list(...)
  inputs <- modifyList(inputs, dots)

  # Ensure `cycMethod = "ARS"` and print message if set manually
  inputs$cycMethod = "ARS"
  if (!is.null(dots$cycMethod) && dots$cycMethod != "ARS") {
    message(
      paste0(
        "'ARSER' was selected as the 'method', but the 'cycMethod' argument in ",
        "`MetaCycle::meta2d()` was manually set to '",
        dots$cycMethod,
        "'. The specified 'method' will take precendce and the defined ",
        "'cycMethod' will be ignored. To use a different algorithm, please set ",
        "the 'method' argument of clockworks accordingly."
      )
    )
  }

  # Run rhythmicity analysis
  ls_res <- do.call(MetaCycle::meta2d, inputs)

  # Add feature IDs and group to results df (if not there already)
  ls_res <- lapply(ls_res, function(x) cbind(x, group = grp))

  # Return results
  return(ls_res)
}
