#' Run meta3d rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_meta3d()`
#' @param method_args Additional parameters passed to `MetaCycle::meta3d()`
#'
#' @importFrom MetaCycle meta3d
#'
#' @returns A list
execute_meta3d <- function(inputs, method_args = list()) {
  # TODO: Figure out what to do about `parallelize` and `nCores`

  # Combine and overwrite inputs with method_args
  inputs <- utils::modifyList(inputs, method_args)

  # Run rhythmicity analysis
  ls_res <- do.call(MetaCycle::meta3d, inputs)

  # Get temporary file name pattern by extracting everything after
  # "meta3d_input_design_" and before the file extension
  tmp_file_pattern <- sub(
    "^meta3d_input_design_?(.*)\\.[^.]+$",
    "\\1",
    basename(inputs$designfile)
  )

  # Get results files from output directory that match the temporary file name pattern
  in_dir <- inputs$outdir
  res_files <- list.files(
    in_dir,
    pattern = "meta3dGroupID.*$",
    full.names = TRUE
  )
  res_files <- res_files[grepl(tmp_file_pattern, res_files)]

  ls_res <- lapply(res_files, function(file) {
    res <- read.table(file, header = TRUE, sep = "\t", quote = "\"", dec = ".")
    return(res)
  })

  # Extract group names from file names and assign to list
  group_names <- gsub(
    "meta3dGroupID_(.*)_meta3d.*$",
    "\\1",
    basename(res_files)
  )
  names(ls_res) <- group_names

  # Add group name as a column to each data frame in the list
  ls_res <- lapply(names(ls_res), function(group) {
    df <- ls_res[[group]]
    df <- cbind(df[1], group = group, df[-1])
    return(df)
  })
  names(ls_res) <- group_names

  # Return results
  return(ls_res)
}
