#' Run RepeatedCircadian rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_repeatedcircadian()`
#' @param ... Additional parameters passed to
#'   `RepeatedCircadian::rpt_rhythmicity()`
#'
#' @import RepeatedCircadian
#' @importFrom future.apply future_lapply
#'
#' @returns A data frame
execute_repeatedcircadian <- function(inputs, ...) {
  # Run rhythmicity detection for each feature separately
  ls_res <- future_lapply(1:inputs$n_features, function(feature) {
    yy <- as.numeric(inputs$data_filt[feature, ])
    res <- rpt_rhythmicity(
      tt = inputs$tt,
      yy = yy,
      id = inputs$subj_id,
      period = inputs$period,
      ...
    )
    unlist(res)
  })

  # Turn results list into data frame
  df_res_raw = as.data.frame(do.call(rbind, ls_res))

  # Add feautre IDs and group to results df
  df_res = data.frame(feature = rownames(inputs$data_filt),
                      group = inputs$group,
                      df_res_raw)

  # Return results
  return(df_res)
}
