#' Run dryR rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_dryr()`
#' @param grp Group that is analysed
#' @param method_args, Additional parameters passed to `dryR::f_24()` or
#'   `dryR::dryseq_single`
#'
#' @importFrom dryR f_24 dryseq_single
#' @importFrom DESeq2 DESeqDataSetFromMatrix DESeq results counts
#'
#' @returns A data frame
execute_dryr <- function(inputs, grp, method_args = list()) {
  # Combine and overwrite inputs with method_args
  inputs <- utils::modifyList(inputs, method_args)

  # Run rhythmicity analysis
  if (inputs$method == "f_24") {
    inputs$method <- NULL
    ls_res <- do.call(dryR::f_24, inputs)
  } else if (inputs$method == "dryseq_single") {
    # Load DESeq2 if not already loaded, as it is required for dryseq_single
    # Note: Using `@importFrom` is not enough, because `dryseq_single()` calls
    # `DESeq()` instead of `DESeq2::DESeq()`
    if (!"package:DESeq2" %in% search()) {
      attachNamespace("DESeq2")
    }

    inputs$method <- NULL
    ls_res <- do.call(dryR::dryseq_single, inputs)
  }

  # Return results
  return(ls_res)
}
