#' Run dryR rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_dryr()`
#' @param method_args, Additional parameters passed to `dryR::f_24()` or
#'   `dryR::dryseq_single`
#'
#' @importFrom dryR f_24 dryseq_single
#' @importFrom DESeq2 DESeqDataSetFromMatrix DESeq
#' @import DESeq2
#'
#' @returns A data frame
execute_dryr <- function(inputs, grp, method_args = list()) {
  # Combine and overwrite inputs with method_args
  inputs <- modifyList(inputs, method_args)

  # Run rhythmicity analysis
  if (inputs$method == "f_24") {
    inputs$method <- NULL
    ls_res <- do.call(dryR::f_24, inputs)

    # # Create output data frame
    # df_res <- data.frame(
    #   ls_res$parameters,
    #   group = grp
    # )

  } else if (inputs$method == "dryseq_single") {
    inputs$method <- NULL
    ls_res <- do.call(dryR::dryseq_single, inputs)
  }

  # Return results
  return(ls_res)
}
