#' Run diffCircadian rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_diffcircadian()`
#' @param method_args Additional parameters passed to
#'   `diffCircadian::LR_rhythmicity()`
#'
#' @import diffCircadian
#' @import future
#' @importFrom future.apply future_apply
#'
#' @returns A data frame
execute_diffcircadian <- function(inputs, method_args = list()) {
  # Get data set
  dat <- inputs$dat
  inputs$dat <- NULL

  # Combine and overwrite inputs with method_args
  inputs <- modifyList(inputs, method_args)

  # Get names of columns with values
  val_cols <- grep("^T\\d+_R", colnames(dat), value = TRUE)

  # Get time points
  tt <- as.numeric(sub("T(\\d+)_.*", "\\1", val_cols))

  # Run rhythmicity detection for each gene of each group
  df_res <- future_apply(dat, 1, function(feat) {
    # Initiate list of inputs
    inputs_tmp <- inputs

    # Extract values
    yy <- as.numeric(feat[val_cols])

    # Remove missing values and add to input list
    inputs_tmp$yy <- yy[!is.na(yy)]
    inputs_tmp$tt <- tt[!is.na(yy)]

    # Run analysis
    res <- do.call(diffCircadian::LR_rhythmicity, inputs_tmp)

    return(unlist(res))
  }, simplify = TRUE)

  # Convert to data frame
  df_res <- as.data.frame(t(df_res))

  # Add features and groups
  df_res <- data.frame(feature = dat$feature, group = dat$group, df_res)

  # Return results
  return(df_res)
}
