#' Run LimoRhyde rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_limorhyde()`
#' @param type Data type, "norm" or "count".
#' @param method_args Additional parameters passed to `limma::lmFit()` or
#'   `edgeR::vommLmFit()` depending on `type`.
#'
#' @importFrom limma lmFit eBayes topTable
#' @importFrom edgeR voomLmFit
#'
#' @returns A data frame
execute_limorhyde <- function(inputs, type, method_args = list()) {
  # Combine and overwrite inputs with method_args
  inputs <- modifyList(inputs, method_args)

  # Run rhythmicity analysis
  if (type == "norm") {
    fit <- do.call(limma::lmFit, inputs)
    fit <- limma::eBayes(fit, trend = TRUE)

    # Extract results
    res <- limma::topTable(fit, coef = 2:3, number = Inf)

  } else if (type == "count") {
    edgeR::voomLmFit()

  } else {
    stop(paste0("'type' must be either 'norm' or 'count'"))
  }

  # Add feature IDs and group to results df (if not there already)
  df_res = data.frame(feature = ,
                      group = grp,
                      df_res)

  # Return results
  return(df_res)
}
