#' Run CircaN rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_circan()`
#' @param grp Group that is analysed
#' @param method_args Additional parameters passed to `CircaN::circan()`
#'
#' @import CircaN
#' @import nlme
#'
#' @returns A data frame
execute_circan <- function(inputs, grp, method_args) {
  # Prevent "object 'vec' not found" error if one curve type can't be fit
  # TODO: Figure out if this is necessary (was in the benchmark) or of there is
  # a better way to do this.
  # TODO: FIGURE OUT WHAT TO DO IF THE USER HAS OBJECTS CALLED `vec`, `akaike`
  # OR `r` IN THEIR ENVIRONMENT. MAYBE RENAME THEIR VARIABLES, DEFINE THESE
  # HERE, REMOVE THESE AND RENAME THEIRS BACK
  vec <<- rep(NA, times = 12)
  akaike <<- c(NA, NA)
  r <<- NA

  # Combine and overwrite inputs with method_args
  inputs <- modifyList(inputs, method_args)

  # Run rhythmicity analysis
  df_res <- suppressWarnings(do.call(CircaN::circan, inputs))

  # Add feature IDs and group to results df
  df_res$group <- grp

  # Return results
  return(df_res)
}
