#' Run GeneCycle rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_genecycle()`
#' @param method_args, Additional parameters passed to
#'   `GeneCycle::robust.spectrum()` and `GeneCycle::robust.g.test()`
#'
#' @importFrom GeneCycle robust.spectrum robust.g.test
#'
#' @returns A data frame
execute_genecycle <- function(inputs, grp, method_args = list()) {
  # TODO: In the main clockworks function, inform the user that if they want to
  # run 'rank' GeneCycle with an unknown period they should set `index = NA` in
  # method_args. If they want to run 'regression' GeneCycle with an unknown
  # period, they should set `periodicity.time = FALSE`, otherwise the enetered
  # period will be used.

  # Combine method_args with user input ----
  # Get list of possible arguments for the two functions
  spectrum_argnames <- formalArgs(GeneCycle::robust.spectrum)
  gtest_argnames <- formalArgs(GeneCycle::robust.g.test)

  # Get user input
  spectrum_user_args <- method_args[intersect(spectrum_argnames, names(method_args))]
  gtest_user_args <- method_args[intersect(gtest_argnames, names(method_args))]

  # Overwrite default inputs with user inputs
  spectrum_inputs <- modifyList(inputs$spectrum, spectrum_user_args)
  gtest_inputs <- modifyList(inputs$gtest, gtest_user_args)

  # If user set 'index = NA' remove it (NA or NULL do not work, index just needs
  # to be missing for expected behaviour)
  if (is.na(gtest_inputs$index)) gtest_inputs$index <- NULL


  # Determine how to run analysis ----
  algorithm <- spectrum_inputs$algorithm  # Note: Could also be gtest_inputs$algorithm
  if (algorithm == "regression") gtest_inputs$perm <- TRUE
  approach <- ifelse(gtest_inputs$perm == TRUE, "permutation", "montecarlo")
  known_period <- switch(
    algorithm,
    rank = ifelse("index" %in% names(gtest_inputs), TRUE, FALSE),
    regression = ifelse(spectrum_inputs$periodicity.time == FALSE, FALSE, TRUE),
    stop("'algorithm' must be 'rank' or 'regression'.")
  )

  cat("\nalgorithm:\t", algorithm)
  cat("\napproach:\t", approach)
  cat("\nknown_period:\t", known_period)

  # Run analysis ----
  # Note: Whether the period is known or not for rank-based approach is
  # determined by the existence or absence of gtest_inputs$index, so no if
  # statement is necessary. For the regression-based approach it's a bit more
  # complicated, however it's easier in the sense that the Monte Carlo approach
  # is not available, only permutation.
  if (algorithm == "rank" && approach == "montecarlo") {
    y <- do.call(GeneCycle::robust.spectrum, spectrum_inputs)
    gtest_inputs$y <- y
    pvals <- do.call(GeneCycle::robust.g.test, gtest_inputs)

    # Delete file created by robust.spectrum()
    unlink(paste0("g_pop_length_", nrow(y), ".txt"))
    unlink(paste0("g_pop_length_", nrow(y), "indexed.txt"))

  } else if (algorithm == "rank" && approach == "permutation") {
    y <- do.call(GeneCycle::robust.spectrum, spectrum_inputs)
    gtest_inputs$y <- y
    gtest_inputs$x <- spectrum_inputs$x
    pvals <- do.call(GeneCycle::robust.g.test, gtest_inputs)

  } else if (algorithm == "regression" && known_period == FALSE) {
    y <- do.call(GeneCycle::robust.spectrum, spectrum_inputs)
    gtest_inputs$y <- y
    gtest_inputs$x <- spectrum_inputs$x
    pvals <- do.call(GeneCycle::robust.g.test, gtest_inputs)

  } else if (algorithm == "regression" && known_period == TRUE) {
    # In this (and only this) case, `robust.spectrum` returns p-values.
    pvals <- do.call(GeneCycle::robust.spectrum, spectrum_inputs)
  }

  # Add feature IDs and group to results df (if not there already)
  df_res = data.frame(feature = colnames(inputs$spectrum$x),
                      group = grp,
                      pval = pvals)

  # Return results
  return(df_res)
}
