#' Run RepeatedCircadian rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_repeatedcircadian()`
#' @param grp Group that is analysed
#' @param method_args Additional parameters passed to
#'   `RepeatedCircadian::rpt_rhythmicity()`
#'
#' @import RepeatedCircadian
#' @importFrom future.apply future_lapply
#'
#' @returns A data frame
execute_repeatedcircadian <- function(inputs, grp, method_args = list()) {
  # Get data set
  dat <- inputs$dat
  inputs$dat <- NULL

  # Combine and overwrite inputs with method_args
  inputs <- modifyList(inputs, method_args)

  # Run rhythmicity detection for each feature separately
  ls_res <- future_lapply(1:nrow(dat), function(feature) {
    inputs_tmp <- inputs
    inputs_tmp$yy <- as.numeric(dat[feature, ])
    res <- do.call(RepeatedCircadian::rpt_rhythmicity, inputs_tmp)
    unlist(res)
  })

  # Turn results list into data frame
  df_res_raw = as.data.frame(do.call(rbind, ls_res))

  # Add feautre IDs and group to results df
  df_res = data.frame(feature = rownames(dat),
                      df_res_raw,
                      period = inputs$period,
                      group = grp)

  # Return results
  return(df_res)
}
