#' Run JTK_CYCLE rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_jtkcycle()`
#' @param grp Group that is analysed
#' @param method_args Additional parameters passed to `MetaCycle::meta2d()`
#'
#' @importFrom MetaCycle meta2d
#'
#' @returns A list
execute_jtkcycle <- function(inputs, grp, method_args = list()) {
  # Combine and overwrite inputs with method_args
  inputs <- modifyList(inputs, method_args)

  # Run rhythmicity analysis
  ls_res <- do.call(MetaCycle::meta2d, inputs)

  # Add feature IDs and group to results
  ls_res <- lapply(ls_res, function(x) {
    if (is.data.frame(x)) cbind(x, group = grp)
  })

  # Return results
  return(ls_res)
}
