#' Run TimeCycle rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_timecycle()`
#' @param grp Group that is analysed
#' @param method_args Additional parameters passed to `TimeCycle::TimeCycle()`
#'
#' @importFrom TimeCycle TimeCycle
#'
#' @returns A data frame
execute_timecycle <- function(inputs, grp, method_args = list()) {
  # Combine and overwrite inputs with method_args
  inputs <- utils::modifyList(inputs, method_args)

  if (inputs$maxLag == 3 && !"maxLag" %in% method_args) {
    message(
      "Running TimeCycle with 'maxLag = 3' instead of 5 (default) because ",
      "sampling interval is greater than 2, or the number of cycles is less ",
      "than 2. If you want to change this, set 'maxLag' in 'method_args'."
    )
  }

  # Run rhythmicity analysis
  df_res <- do.call(TimeCycle::TimeCycle, inputs)

  # Add feature IDs and group to results df (if not there already)
  df_res <- data.frame(df_res, group = grp)

  # Return results
  return(df_res)
}
