#' Run RAIN rhythmicity detection in parallel
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_rain()`
#' @param grp Group that is analysed
#' @param method_args Additional parameters passed to `rain::rain`
#'
#' @import rain
#' @importFrom future nbrOfWorkers
#' @importFrom future.apply future_lapply
#'
#' @returns A data frame
execute_rain_parallel <- function(inputs, grp, method_args = list()) {
  # Combine and overwrite inputs with method_args
  inputs <- utils::modifyList(inputs, method_args)

  # Inform user that we are overwriting RAIN's default behaviour
  if (inputs$method == "longitudinal" && !"method" %in% method_args) {
    message(
      "Running RAIN with 'method = \"longitudinal\"' because the data contain ",
      "repeated measures. If you want to change this, set 'method_args = ",
      "list(method = \"independent\")'"
    )
  }

  # Get number of available workers for parallel processing
  n_workers <- future::nbrOfWorkers()
  n_splits <- min(n_workers, ncol(inputs$x))

  # Create a list of inputs, splitting the features into n_splits groups for parallel processing
  list_inputs <- lapply(1:n_splits, function(i) {
    list(
      x = inputs$x[, seq(i, ncol(inputs$x), by = n_splits), drop = FALSE]
    )
  })

  # Run analysis in parallel using future.apply
  df_res_list <- future.apply::future_lapply(
    list_inputs,
    function(chunk_input) {
      # Combine chunk-specific input with other inputs
      feature_inputs <- c(chunk_input, inputs[setdiff(names(inputs), "x")])
      # Run RAIN for this chunk
      do.call(rain::rain, feature_inputs)
    }
  )

  # Combine results into a single data frame
  df_res <- do.call(rbind, df_res_list)

  # Restore original order of features
  df_res <- df_res[match(colnames(inputs$x), rownames(df_res)), ]

  # Add feature IDs and group to results df (if not there already)
  df_res = data.frame(feature = colnames(inputs$x), df_res, group = grp)

  # Return results
  return(df_res)
}
