#' Run ARSER rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_arser()`
#' @param ... Additional parameters passed to `MetaCycle::meta2d()`
#'
#' @importFrom MetaCycle meta2d
#'
#' @returns A list
execute_arser <- function(inputs, ...) {
  # TODO: Figure out what to do about `parallelize` and `nCores`

  # Run rhythmicity analysis
  ls_res <- MetaCycle::meta2d(
    inDF = inputs$inDF,
    infile = paste("Group", inputs$group), # Using inDF, but can't be empty
    filestyle = "csv", # Irrelevant, but needs to be either "csv" or "txt"
    timepoints = inputs$timepoints,
    minper = inputs$minper, # TODO: Is this relevant for ARSER?
    maxper = inputs$maxper, # TODO: Is this relevant for ARSER?
    ARSdefaultPer = mean(inputs$minper, inputs$maxper),  # TODO: What if user defines this in "..." ?
    cycMethod = "ARS",
    parallelize = FALSE,
    nCores = 1,
    outputFile = FALSE,
    releaseNote = TRUE, # Probably set to FALSE?
    ...
  )

  # Add feature IDs and group to results df (if not there already)
  ls_res <- lapply(ls_res, function(x) cbind(x, group = inputs$group))

  # Return results
  return(ls_res)
}
