#' Run Lomb-Scargle rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_ls()`
#' @param ... Additional parameters passed to `MetaCycle::meta2d()`
#'
#' @importFrom MetaCycle meta2d
#'
#' @returns A list
execute_ls <- function(inputs, ...) {
  # TODO: Figure out what to do about `parallelize` and `nCores`

  # Run rhythmicity analysis
  ls_res <- MetaCycle::meta2d(
    inDF = inputs$inDF,
    infile = paste("Group", inputs$group), # Using inDF, but can't be empty
    filestyle = "csv", # Irrelevant, but needs to be either "csv" or "txt"
    timepoints = inputs$timepoints,
    minper = inputs$minper,
    maxper = inputs$maxper,
    cycMethod = "LS",
    parallelize = FALSE,
    nCores = 1,
    outputFile = FALSE,
    releaseNote = TRUE, # Probably set to FALSE?
    ...
  )

  # Add feature IDs and group to results
  ls_res <- lapply(ls_res, function(x) {
    if (is.data.frame(x)) cbind(x, group = grp)
  })

  # Return results
  return(ls_res)
}
