#' Run RAIN rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_rain()`
#' @param grp Group that is analysed
#' @param method_args Additional parameters passed to `rain::rain`
#'
#' @import rain
#'
#' @returns A data frame
execute_rain <- function(inputs, grp, method_args = list()) {
  # Combine and overwrite inputs with method_args
  inputs <- utils::modifyList(inputs, method_args)

  # Inform user that we are overwriting RAIN's default behaviour
  if (inputs$method == "longitudinal" && !"method" %in% method_args) {
    message(
      "Running RAIN with 'method = \"longitudinal\"' because the data contain ",
      "repeated measures. If you want to change this, set 'method_args = ",
      "list(method = \"independent\")'"
    )
  }

  # Run rhythmicity analysis
  df_res = do.call(rain::rain, inputs)

  # Add feature IDs and group to results df (if not there already)
  df_res = data.frame(feature = colnames(inputs$x), df_res, group = grp)

  # Return results
  return(df_res)
}
