#' Run meta2d rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_meta2d()`
#' @param grp Group that is being analysed
#' @param ... Additional parameters passed to `MetaCycle::meta2d()`
#'
#' @importFrom MetaCycle meta2d
#'
#' @returns A list
execute_meta2d <- function(inputs, grp, ...) {
  # TODO: Figure out what to do about `parallelize` and `nCores`

  # Combine and overwrite inputs with `...`
  dots <- list(...)
  inputs <- modifyList(inputs, dots)

  # Run rhythmicity analysis
  ls_res <- do.call(MetaCycle::meta2d, inputs)

  # Add feature IDs and group to results
  ls_res <- lapply(ls_res, function(x) {
    if (is.data.frame(x)) cbind(x, group = grp)
  })

  # Return results
  return(ls_res)
}
