#' Run CircaN rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_circan()`
#' @param ... Additional parameters passed to
#'   `CircaN::circan()`
#'
#' @import CircaN
#' @import nlme
#'
#' @returns A data frame
run_circan <- function(inputs, ...) {
  # Prevent "object 'vec' not found" error if one curve type can't be fit
  # TODO: Figure out if this is necessary (was in the benchmark) or of there is
  # a better way to do this.
  # TODO: FIGURE OUT WHAT TO DO IF THE USER HAS OBJECTS CALLED `vec`, `akaike`
  # OR `r` IN THEIR ENVIRONMENT. MAYBE RENAME THEIR VARIABLES, DEFINE THESE
  # HERE, REMOVE THESE AND RENAME THEIRS BACK
  vec <<- rep(NA, times = 12)
  akaike <<- c(NA, NA)
  r <<- NA

  # Run rhythmicity analysis
  df_res = suppressWarnings(CircaN::circan(
    data = inputs$df_data,
    meta = inputs$df_metadata,
    min_per = inputs$min_per,
    max_per = inputs$max_per,
    ...
  ))

  # Add feature IDs and group to results df
  df_res$group = inputs$group

  # Return results
  return(df_res)
}
