#' Run CircaN rhythmicity detection
#'
#' @param inputs Inputs for rhythmicity detection function generated by
#'   `prepare_circan()`
#' @param ... Additional parameters passed to
#'   `CircaN::circan()`
#'
#' @import CircaN
#' @import nlme
#' @importFrom future.apply future_lapply
#'
#' @returns A data frame
run_circan <- function(inputs, ...) {
  # Prevent "object 'vec' not found" error if one curve type can't be fit
  # TODO: Figure out if this is necessary (was in the benchmark) or of there is
  # a better way to do this
  vec <<- rep(NA, times = 12)
  akaike <<- c(NA, NA)
  r <<- NA

  # R

  # Add feautre IDs and group to results df
  df_res = data.frame(feature = rownames(inputs$data_filt),
                      group = inputs$group,
                      df_res_raw)

  # Return results
  return(df_res)
}
